name: harry_potter
description: Harry Potter for Lego demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  i69n: ^2.1.0
  injectable: ^2.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  injectable_generator: ^2.4.0